/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import koneksi.koneksi;
/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {
koneksi conn;
private final Image iconImg;

    private void hakakses(){
        String user = UserSession.getUserLogin();
    }   

    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
         public void actionPerformed(ActionEvent evt){}
        };
        new Timer(1000, taskPerformer).start();
    }
 
    public void setTanggal(){
        Date skrg = new Date(); 
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        dateLbl.setText(sdf.format(skrg));
    }

 
    /**
     * Creates new form MenuUtama
     */
    public Dashboard() {
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        
        initComponents();
        conn = new koneksi();
        hakakses();
        setJam();
        setTanggal();
       
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        iconImg = new ImageIcon(getClass().getResource("/gambar/favicon.jpg")).getImage();
        setIconImage(iconImg);
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("db_koperasi?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        dateLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        masterMenu = new javax.swing.JMenu();
        masterAnggota = new javax.swing.JMenuItem();
        masterPengguna = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        simpananButton = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenu();
        lgooutBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Koperasi karyawan PT. Mitra Ihsan Sejahtera - Dashboard");
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dateLbl.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLbl.setText("date");
        dateLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        menuBar.setBackground(new java.awt.Color(1, 138, 51));
        menuBar.setBorderPainted(false);
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        menuBar.setName(""); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(400, 42));
        menuBar.setOpaque(true);

        masterMenu.setText("Master");
        masterMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        masterMenu.setMargin(new java.awt.Insets(2, 2, 2, 4));
        masterMenu.setMaximumSize(new java.awt.Dimension(100, 32767));
        masterMenu.setPreferredSize(new java.awt.Dimension(70, 20));
        masterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterMenuActionPerformed(evt);
            }
        });

        masterAnggota.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        masterAnggota.setText("Data Anggota");
        masterAnggota.setPreferredSize(new java.awt.Dimension(127, 30));
        masterAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterAnggotaActionPerformed(evt);
            }
        });
        masterMenu.add(masterAnggota);

        masterPengguna.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        masterPengguna.setText("Data Pengguna");
        masterPengguna.setPreferredSize(new java.awt.Dimension(137, 30));
        masterPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterPenggunaActionPerformed(evt);
            }
        });
        masterMenu.add(masterPengguna);

        menuBar.add(masterMenu);

        transaksiMenu.setText("Transaksi");
        transaksiMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        transaksiMenu.setMaximumSize(new java.awt.Dimension(120, 32767));
        transaksiMenu.setPreferredSize(new java.awt.Dimension(90, 20));
        transaksiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiMenuActionPerformed(evt);
            }
        });

        simpananButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        simpananButton.setText("Simpanan");
        simpananButton.setPreferredSize(new java.awt.Dimension(125, 30));
        simpananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpananButtonActionPerformed(evt);
            }
        });
        transaksiMenu.add(simpananButton);

        jMenuItem4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem4.setText("Pinjaman");
        jMenuItem4.setPreferredSize(new java.awt.Dimension(120, 30));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        transaksiMenu.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem5.setText("Angsuran");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(120, 30));
        jMenuItem5.setRequestFocusEnabled(false);
        transaksiMenu.add(jMenuItem5);

        menuBar.add(transaksiMenu);

        laporanMenu.setText("Laporan");
        laporanMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        laporanMenu.setPreferredSize(new java.awt.Dimension(100, 24));

        jMenuItem6.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem6.setText("Data Anggota");
        jMenuItem6.setPreferredSize(new java.awt.Dimension(135, 30));
        laporanMenu.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem7.setText("Data Simpanan");
        jMenuItem7.setPreferredSize(new java.awt.Dimension(143, 30));
        laporanMenu.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem8.setText("Data Pinjaman");
        jMenuItem8.setPreferredSize(new java.awt.Dimension(143, 30));
        laporanMenu.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jMenuItem9.setText("Data Angsuran");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(143, 30));
        jMenuItem9.setRequestFocusEnabled(false);
        laporanMenu.add(jMenuItem9);

        menuBar.add(laporanMenu);

        logoutMenu.setBackground(new java.awt.Color(255, 255, 0));
        logoutMenu.setBorder(null);
        logoutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user-4.png"))); // NOI18N
        logoutMenu.setText(UserSession.getUserLogin());
        logoutMenu.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        logoutMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutMenu.setIconTextGap(0);
        logoutMenu.setInheritsPopupMenu(true);
        logoutMenu.setPreferredSize(new java.awt.Dimension(150, 28));

        lgooutBtn.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lgooutBtn.setText("Keluar");
        lgooutBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        lgooutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgooutBtnActionPerformed(evt);
            }
        });
        logoutMenu.add(lgooutBtn);

        menuBar.add(Box.createHorizontalGlue());

        menuBar.add(logoutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(999, Short.MAX_VALUE)
                .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLbl)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transaksiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiMenuActionPerformed
        // TODO add your handling code here:
        Simpanan simpanan = new Simpanan();
        simpanan.setVisible(true);
    }//GEN-LAST:event_transaksiMenuActionPerformed

    private void masterAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterAnggotaActionPerformed
        // TODO add your handling code here:
       Anggota anggota = new Anggota();
       anggota.setVisible(true);
        
    }//GEN-LAST:event_masterAnggotaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Pinjaman pinjaman = new Pinjaman();
        pinjaman.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void lgooutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgooutBtnActionPerformed
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);       
    }//GEN-LAST:event_lgooutBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan menutup aplikasi ini?","Tutup Aplikasi?",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE) ==JOptionPane.YES_OPTION)
            System.exit(0);
        else
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosing

    private void masterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterMenuActionPerformed

    private void masterPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterPenggunaActionPerformed
        // TODO add your handling code here:
        
        Pengguna pengguna = new Pengguna();
        pengguna.setVisible(true);
      
    }//GEN-LAST:event_masterPenggunaActionPerformed

    private void simpananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpananButtonActionPerformed
        // TODO add your handling code here:
        Simpanan simpanan = new Simpanan();
        simpanan.setVisible(true);
    }//GEN-LAST:event_simpananButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLbl;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem lgooutBtn;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenuItem masterAnggota;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenuItem masterPengguna;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem simpananButton;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
